version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:17"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:27"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 3
